module.exports = {
    id: "",
    firstname: "",
    lastname: "",
    address: "",
    email: "",
    phone: "",
    mobile: "",
    zipCode: "",
    city: "",
    situation: "",
    numberOfChild: "",
    userId: "",
    activity: "",
    age: "",
    guarentee: "",
    mutual: "",
    bank: "",
    availability: "",
    createdAt: new Date(),
    updatedAt: new Date()
}